
package io.devotel.profileservice.soap.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UserPort", targetNamespace = "http://devotel.io/user-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserPort {


    /**
     * 
     * @param getUserByIdRequest
     * @return
     *     returns io.devotel.profileservice.soap.wsdl.GetUserByIdResponse
     */
    @WebMethod
    @WebResult(name = "getUserByIdResponse", targetNamespace = "http://devotel.io/userservice", partName = "getUserByIdResponse")
    public GetUserByIdResponse getUserById(
        @WebParam(name = "getUserByIdRequest", targetNamespace = "http://devotel.io/userservice", partName = "getUserByIdRequest")
        GetUserByIdRequest getUserByIdRequest);

}
