
package io.devotel.profileservice.soap.wsdl;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UserPortService", targetNamespace = "http://devotel.io/user-service", wsdlLocation = "file:/C:/Users/vahid/Desktop/project/profile-service/src/main/resources/wsdl/userService.wsdl")
public class UserPortService
    extends Service
{

    private static final URL USERPORTSERVICE_WSDL_LOCATION;
    private static final WebServiceException USERPORTSERVICE_EXCEPTION;
    private static final QName USERPORTSERVICE_QNAME = new QName("http://devotel.io/user-service", "UserPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/vahid/Desktop/project/profile-service/src/main/resources/wsdl/userService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERPORTSERVICE_WSDL_LOCATION = url;
        USERPORTSERVICE_EXCEPTION = e;
    }

    public UserPortService() {
        super(__getWsdlLocation(), USERPORTSERVICE_QNAME);
    }

    public UserPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERPORTSERVICE_QNAME, features);
    }

    public UserPortService(URL wsdlLocation) {
        super(wsdlLocation, USERPORTSERVICE_QNAME);
    }

    public UserPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERPORTSERVICE_QNAME, features);
    }

    public UserPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserPort
     */
    @WebEndpoint(name = "UserPortSoap11")
    public UserPort getUserPortSoap11() {
        return super.getPort(new QName("http://devotel.io/user-service", "UserPortSoap11"), UserPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserPort
     */
    @WebEndpoint(name = "UserPortSoap11")
    public UserPort getUserPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://devotel.io/user-service", "UserPortSoap11"), UserPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERPORTSERVICE_EXCEPTION!= null) {
            throw USERPORTSERVICE_EXCEPTION;
        }
        return USERPORTSERVICE_WSDL_LOCATION;
    }

}
